import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey || apiKey.includes('your_gemini_api_key_here')) {
      return NextResponse.json(
        { error: 'Gemini API key is not configured on the server.' },
        { status: 400 }
      );
    }

    const body = await req.json();
    const { imageBase64, action, userPrompt } = body;

    if (!imageBase64) {
      return NextResponse.json({ error: 'Image data is required.' }, { status: 400 });
    }

    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, '');

    // ===== SEGMENTATION MASK (Image Generation) =====
    if (action === 'segment-mask') {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 30000); // 30s for image gen

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          signal: controller.signal,
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: `Generate a binary segmentation mask for this image.

Rules:
- Output ONLY a black and white image, same dimensions as the input.
- WHITE (#FFFFFF) = the main foreground subject (person, face, hair, body, clothing, accessories). Include ALL of the subject including hair edges and fine details.
- BLACK (#000000) = the background (everything behind the subject: walls, curtains, furniture, sky, floor, objects).
- Make the boundary between subject and background as precise as possible.
- Do NOT include any text, labels, or annotations in the output image.
- The output must be ONLY the mask image, nothing else.`,
                  },
                  {
                    inline_data: {
                      mime_type: 'image/jpeg',
                      data: cleanBase64,
                    },
                  },
                ],
              },
            ],
            generationConfig: {
              responseModalities: ['IMAGE'],
            },
          }),
        }
      );

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        return NextResponse.json(
          { error: 'Gemini Mask API Error', details: errorText },
          { status: response.status }
        );
      }

      const data = await response.json();
      const parts = data.candidates?.[0]?.content?.parts;

      if (parts) {
        for (const part of parts) {
          if (part.inline_data) {
            const maskBase64 = `data:${part.inline_data.mime_type};base64,${part.inline_data.data}`;
            return NextResponse.json({ success: true, maskImage: maskBase64 });
          }
        }
      }

      return NextResponse.json({ error: 'No mask image generated by Gemini.' }, { status: 500 });
    }

    // ===== JSON-based actions (text output) =====
    let promptText = '';

    if (action === 'remove-background') {
      promptText = `Locate the main foreground subject (person, face, or primary object) in this image. Return ONLY a valid JSON object:
{
  "subjectBox": [ymin, xmin, ymax, xmax], // 0-1000 normalized coordinates
  "dominantBgColor": "#hexcolor"
}`;
    } else if (action === 'auto-enhance') {
      promptText = `Analyze this image. Return ONLY a valid JSON object:
{
  "subjectBox": [ymin, xmin, ymax, xmax],
  "recommendedPreset": "ig-portrait" | "ig-square" | "tiktok-story" | "yt-thumbnail" | "original",
  "suggestedAdjustments": {
    "brightness": 0,
    "contrast": 10,
    "saturation": 5,
    "warmth": 0,
    "vignette": 10
  },
  "aiSummary": "Brief 1-sentence description of the image"
}`;
    } else if (action === 'generate-caption') {
      promptText = `Analyze this image and generate engaging social media content. Return ONLY a valid JSON object:
{
  "title": "Short catchy title",
  "caption": "2-3 sentence engaging post caption with emojis",
  "hashtags": ["#tag1", "#tag2", "#tag3", "#tag4", "#tag5"]
}`;
    } else if (action === 'prompt-edit') {
      promptText = `User request: "${userPrompt || 'Enhance photo'}". Convert the request into color grading parameters. Return ONLY a valid JSON object:
{
  "brightness": 10,
  "contrast": 10,
  "saturation": 5,
  "warmth": 5,
  "vignette": 10,
  "explanation": "Brief explanation of how the style was applied"
}`;
    } else {
      return NextResponse.json({ error: 'Invalid action requested.' }, { status: 400 });
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 12000);

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        signal: controller.signal,
        body: JSON.stringify({
          contents: [
            {
              parts: [
                { text: promptText },
                {
                  inline_data: {
                    mime_type: 'image/jpeg',
                    data: cleanBase64,
                  },
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.1,
            response_mime_type: 'application/json',
          },
        }),
      }
    );

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorText = await response.text();
      return NextResponse.json(
        { error: 'Gemini API Error', details: errorText },
        { status: response.status }
      );
    }

    const data = await response.json();
    const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!resultText) {
      return NextResponse.json({ error: 'Empty response from Gemini AI.' }, { status: 500 });
    }

    try {
      const parsedJson = JSON.parse(resultText);
      return NextResponse.json({ success: true, result: parsedJson });
    } catch {
      return NextResponse.json({ success: true, rawText: resultText });
    }
  } catch (error: any) {
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 });
  }
}
